### ISSUE TITLE
Stopwatch in the background

### ISSUE THREAD

**Issue by dorxelchidote** [BarRaider/streamdeck-stopwatch#1]
Hi! 
I just installed the StopWatch in my Stream Deck and it is awesome! But it would be even better if you can leave the stopwatch running in the background (in the current version, if you change the profile, the stopwatch resets). 
Regards!

**Comment by ScribbleLP** [comment]
Same thing happens when opening and returning from a folder...

**Comment by BarRaider** [comment]
Hi, sorry for the delay in replying.
This is the expected behavior of the SDK. As soon as you leave a profile, the plugin must terminate itself.

**Comment by ScribbleLP** [comment]
Alright thanks...

**Comment by parithon** [comment]
The stopwatch should be able to remember it's state and restart when it comes back into view then.
