### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by kman3107** [BarRaider/streamdeck-stopwatch#18]
Windows 10 Pro OEM.
Computer is on almost 24/7.
Stopwatch Version: 1.6
Streamdeck Software Version: 4.4.1.12187
Streamdeck Firmware Version: 1.02.004
Profile: Default

1. Installed the plugin
2. Saved file to c:\temp\mystopwatch.txt
3. Activated "Clear text file on reset"
4. Activated "Unpausing does not reset"
5. Tested the stopwatch 2-3 times to make sure it worked fine. It did.
6. About 48 hours later it stopped working.

The numbers stopped showing.
When I tried starting it there showed a warning icon.
Tried removing txt file, creating new.
Tried deactivating the options chosen.
Tried copying it.
Tried adding a new stopwatch.

Worked after I uninstalled and reinstalled the plugin from Streamdeck "More Actions"

**Comment by BarRaider** [comment]
Please head over to my Discord server for support
http://discord.barraider.com

**Comment by kman3107** [comment]
I'm not looking for support. I'm telling you about an issue with your program.
And also. Discord is not a feedback/bug report forum. Don't expect me to join discord servers galore just to give feedback or report bugs. I use Discord to chat. And I already have way too many servers joined.

**Comment by BarRaider** [comment]
Sorry accidentally deleted your comment. Got it, thanks for the feedback
