### ISSUE TITLE
Multi action to reset/clear stopwatch

### ISSUE THREAD

**Issue by russellit** [BarRaider/streamdeck-stopwatch#29]
It'd be great if you could add it so the multi action function has the ability to clear stopwatch times. I've using it for timetracking and have it saving the data into a timesheet, but there's no way to automate the clearing of the time

**Comment by BarRaider** [comment]
Hi, a request for multi-action support already exists on Discord (which is where feature requests are tracked) you can upvote the existing request.
http://discord.barraider com
